let data = {
  statusCode: 200,
  message: "Xử lý thành công!",
  content: {
    thongTinPhim: {
      maLichChieu: 16261,
      tenCumRap: "BHD Star Cineplex - Bitexco",
      tenRap: "Rạp 10",
      diaChi: "L3-Bitexco Icon 68, 2 Hải Triều, Q.1",
      tenPhim: "Ted 233",
      hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/ted-233_gp04.jpeg",
      ngayChieu: "01/01/2019",
      gioChieu: "10:01",
    },
    danhSachGhe: [
      {
        maGhe: 50441,
        tenGhe: "01",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "01",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50442,
        tenGhe: "02",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "02",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50443,
        tenGhe: "03",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "03",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50444,
        tenGhe: "04",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "04",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50445,
        tenGhe: "05",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "05",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50446,
        tenGhe: "06",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "06",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50447,
        tenGhe: "07",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "07",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50448,
        tenGhe: "08",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "08",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50449,
        tenGhe: "09",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "09",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50450,
        tenGhe: "10",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "10",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50451,
        tenGhe: "11",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "11",
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: "thinhlam3597",
      },
      {
        maGhe: 50452,
        tenGhe: "12",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "12",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50453,
        tenGhe: "13",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "13",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50454,
        tenGhe: "14",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "14",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50455,
        tenGhe: "15",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "15",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50456,
        tenGhe: "16",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "16",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50457,
        tenGhe: "17",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "17",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50458,
        tenGhe: "18",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "18",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50459,
        tenGhe: "19",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "19",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50460,
        tenGhe: "20",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "20",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50461,
        tenGhe: "21",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "21",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50462,
        tenGhe: "22",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "22",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50463,
        tenGhe: "23",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "23",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50464,
        tenGhe: "24",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "24",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50465,
        tenGhe: "25",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "25",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50466,
        tenGhe: "26",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "26",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50467,
        tenGhe: "27",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "27",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50468,
        tenGhe: "28",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "28",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50469,
        tenGhe: "29",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "29",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50470,
        tenGhe: "30",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "30",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50471,
        tenGhe: "31",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "31",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50472,
        tenGhe: "32",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "32",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50473,
        tenGhe: "33",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "33",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50474,
        tenGhe: "34",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "34",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50475,
        tenGhe: "35",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "35",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50476,
        tenGhe: "36",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "36",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50477,
        tenGhe: "37",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "37",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50478,
        tenGhe: "38",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "38",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50479,
        tenGhe: "39",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "39",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50480,
        tenGhe: "40",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "40",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50481,
        tenGhe: "41",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "41",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50482,
        tenGhe: "42",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "42",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50483,
        tenGhe: "43",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "43",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50484,
        tenGhe: "44",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "44",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50485,
        tenGhe: "45",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "45",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50486,
        tenGhe: "46",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "46",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50487,
        tenGhe: "47",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "47",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50488,
        tenGhe: "48",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "48",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50489,
        tenGhe: "49",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "49",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50490,
        tenGhe: "50",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "50",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50491,
        tenGhe: "51",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "51",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50492,
        tenGhe: "52",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "52",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50493,
        tenGhe: "53",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "53",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50494,
        tenGhe: "54",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "54",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50495,
        tenGhe: "55",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "55",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50496,
        tenGhe: "56",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "56",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50497,
        tenGhe: "57",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "57",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50498,
        tenGhe: "58",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "58",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50499,
        tenGhe: "59",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "59",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50500,
        tenGhe: "60",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "60",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50501,
        tenGhe: "61",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "61",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50502,
        tenGhe: "62",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "62",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50503,
        tenGhe: "63",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "63",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50504,
        tenGhe: "64",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "64",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50505,
        tenGhe: "65",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "65",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50506,
        tenGhe: "66",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "66",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50507,
        tenGhe: "67",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "67",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50508,
        tenGhe: "68",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "68",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50509,
        tenGhe: "69",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "69",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50510,
        tenGhe: "70",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "70",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50511,
        tenGhe: "71",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "71",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50512,
        tenGhe: "72",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "72",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50513,
        tenGhe: "73",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "73",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50514,
        tenGhe: "74",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "74",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50515,
        tenGhe: "75",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "75",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50516,
        tenGhe: "76",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "76",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50517,
        tenGhe: "77",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "77",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50518,
        tenGhe: "78",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "78",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50519,
        tenGhe: "79",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "79",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50520,
        tenGhe: "80",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "80",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50521,
        tenGhe: "81",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "81",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50522,
        tenGhe: "82",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "82",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50523,
        tenGhe: "83",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "83",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50524,
        tenGhe: "84",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "84",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50525,
        tenGhe: "85",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "85",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50526,
        tenGhe: "86",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "86",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50527,
        tenGhe: "87",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "87",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50528,
        tenGhe: "88",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "88",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50529,
        tenGhe: "89",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "89",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50530,
        tenGhe: "90",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "90",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50531,
        tenGhe: "91",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "91",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50532,
        tenGhe: "92",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "92",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50533,
        tenGhe: "93",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "93",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50534,
        tenGhe: "94",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "94",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50535,
        tenGhe: "95",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "95",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50536,
        tenGhe: "96",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "96",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50537,
        tenGhe: "97",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "97",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50538,
        tenGhe: "98",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "98",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50539,
        tenGhe: "99",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "99",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50540,
        tenGhe: "100",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "100",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50541,
        tenGhe: "101",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "101",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50542,
        tenGhe: "102",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "102",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50543,
        tenGhe: "103",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "103",
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: "teishe12",
      },
      {
        maGhe: 50544,
        tenGhe: "104",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "104",
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: "teishe12",
      },
      {
        maGhe: 50545,
        tenGhe: "105",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "105",
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: "teishe12",
      },
      {
        maGhe: 50546,
        tenGhe: "106",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "106",
        giaVe: 90000,
        daDat: true,
        taiKhoanNguoiDat: "teishe12",
      },
      {
        maGhe: 50547,
        tenGhe: "107",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "107",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50548,
        tenGhe: "108",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "108",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50549,
        tenGhe: "109",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "109",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50550,
        tenGhe: "110",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "110",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50551,
        tenGhe: "111",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "111",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50552,
        tenGhe: "112",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "112",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50553,
        tenGhe: "113",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "113",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50554,
        tenGhe: "114",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "114",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50555,
        tenGhe: "115",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "115",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50556,
        tenGhe: "116",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "116",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50557,
        tenGhe: "117",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "117",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50558,
        tenGhe: "118",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "118",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50559,
        tenGhe: "119",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "119",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50560,
        tenGhe: "120",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "120",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50561,
        tenGhe: "121",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "121",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50562,
        tenGhe: "122",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "122",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50563,
        tenGhe: "123",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "123",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50564,
        tenGhe: "124",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "124",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50565,
        tenGhe: "125",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "125",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50566,
        tenGhe: "126",
        maRap: 470,
        loaiGhe: "Vip",
        stt: "126",
        giaVe: 90000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50567,
        tenGhe: "127",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "127",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50568,
        tenGhe: "128",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "128",
        giaVe: 75000,
        daDat: true,
        taiKhoanNguoiDat: "thinhlam3597",
      },
      {
        maGhe: 50569,
        tenGhe: "129",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "129",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50570,
        tenGhe: "130",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "130",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50571,
        tenGhe: "131",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "131",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50572,
        tenGhe: "132",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "132",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50573,
        tenGhe: "133",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "133",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50574,
        tenGhe: "134",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "134",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50575,
        tenGhe: "135",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "135",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50576,
        tenGhe: "136",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "136",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50577,
        tenGhe: "137",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "137",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50578,
        tenGhe: "138",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "138",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50579,
        tenGhe: "139",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "139",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50580,
        tenGhe: "140",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "140",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50581,
        tenGhe: "141",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "141",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50582,
        tenGhe: "142",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "142",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50583,
        tenGhe: "143",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "143",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50584,
        tenGhe: "144",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "144",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50585,
        tenGhe: "145",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "145",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50586,
        tenGhe: "146",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "146",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50587,
        tenGhe: "147",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "147",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50588,
        tenGhe: "148",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "148",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50589,
        tenGhe: "149",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "149",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50590,
        tenGhe: "150",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "150",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50591,
        tenGhe: "151",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "151",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50592,
        tenGhe: "152",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "152",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50593,
        tenGhe: "153",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "153",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50594,
        tenGhe: "154",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "154",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50595,
        tenGhe: "155",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "155",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50596,
        tenGhe: "156",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "156",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50597,
        tenGhe: "157",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "157",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50598,
        tenGhe: "158",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "158",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50599,
        tenGhe: "159",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "159",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
      {
        maGhe: 50600,
        tenGhe: "160",
        maRap: 470,
        loaiGhe: "Thuong",
        stt: "160",
        giaVe: 75000,
        daDat: false,
        taiKhoanNguoiDat: null,
      },
    ],
  },
  dateTime: "2022-10-01T21:12:29.5700355+07:00",
  messageConstants: null,
};
